{{- if and .Values.web.enabled .Values.webIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "maildesk.fullname" . }}-web
  labels:
    {{- include "maildesk.labels" . | nindent 4 }}
  {{- with .Values.webIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webIngress.className }}
  ingressClassName: {{ .Values.webIngress.className }}
  {{- end }}
  {{- if .Values.webIngress.tls }}
  tls:
    {{- range .Values.webIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.webIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "maildesk.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
